services:
  tritonserver: &base
    image: nvcr.io/nvidia/tritonserver:25.10-py3
    network_mode: host
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  tritonserver-sklearn-cpu:
    <<: *base
    build:
      dockerfile: .docker/Sklearn.Dockerfile
      target: tritonserver
    container_name: tritonserver-sklearn-cpu
    image: tritonserver-sklearn:latest

  tritonserver-bert-cpu: &bert
    <<: *base
    build:
      dockerfile: .docker/Bert.Dockerfile
      target: tritonserver
    container_name: tritonserver-bert-cpu
    image: tritonserver-bert:latest

  tritonserver-bert-gpu:
    <<: *bert
    container_name: tritonserver-bert-gpu
    environment:
      - LAUNCH_PARAMETERS=--model-config-name=gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tritonserver-resnet-cpu: &resnet
    <<: *base
    build:
      dockerfile: .docker/ResNet.Dockerfile
      target: tritonserver
    container_name: tritonserver-resnet-cpu
    image: tritonserver-resnet:latest

  tritonserver-resnet-gpu:
    <<: *resnet
    container_name: tritonserver-resnet-gpu
    environment:
      - LAUNCH_PARAMETERS=--model-config-name=gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tritonserver-resnet-gpu-trt:
    <<: *resnet
    container_name: tritonserver-resnet-gpu-trt
    environment:
      - LAUNCH_PARAMETERS=--model-config-name=gpu-trt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tritonserver-client:
    image: nvcr.io/nvidia/tritonserver:25.10-py3-sdk
    network_mode: host
    tty: true
    volumes:
      - ./client:/client
    working_dir: /client

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./metrics/grafana/dashboards:/etc/grafana/dashboards
